/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as PortalBkashCallbackRouteImport } from './routes/portal.bkash-callback'
import { Route as ClientSslczCallbackRouteImport } from './routes/client.sslcz-callback'
import { Route as ClientBkashCallbackRouteImport } from './routes/client.bkash-callback'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as MarketingWebHostingRouteImport } from './routes/_marketing.web-hosting'
import { Route as MarketingVpsRouteImport } from './routes/_marketing.vps'
import { Route as MarketingTermsRouteImport } from './routes/_marketing.terms'
import { Route as MarketingSupportRouteImport } from './routes/_marketing.support'
import { Route as MarketingResellerHostingRouteImport } from './routes/_marketing.reseller-hosting'
import { Route as MarketingRegisterDomainRouteImport } from './routes/_marketing.register-domain'
import { Route as MarketingRefundRouteImport } from './routes/_marketing.refund'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing.privacy'
import { Route as MarketingHelpRouteImport } from './routes/_marketing.help'
import { Route as MarketingEmailHostingRouteImport } from './routes/_marketing.email-hosting'
import { Route as MarketingDomainSearchRouteImport } from './routes/_marketing.domain-search'
import { Route as MarketingContactRouteImport } from './routes/_marketing.contact'
import { Route as MarketingBdixHostingRouteImport } from './routes/_marketing.bdix-hosting'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as AuthenticatedWhmServersRouteImport } from './routes/_authenticated/whm-servers'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServiceCatalogRouteImport } from './routes/_authenticated/service-catalog'
import { Route as AuthenticatedResellersRouteImport } from './routes/_authenticated/resellers'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedReferralsAdminRouteImport } from './routes/_authenticated/referrals-admin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentSettingsRouteImport } from './routes/_authenticated/payment-settings'
import { Route as AuthenticatedPageContentsRouteImport } from './routes/_authenticated/page-contents'
import { Route as AuthenticatedOtherServicesRouteImport } from './routes/_authenticated/other-services'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedKbRouteImport } from './routes/_authenticated/kb'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedInvoiceSettingsRouteImport } from './routes/_authenticated/invoice-settings'
import { Route as AuthenticatedHostingPackagesRouteImport } from './routes/_authenticated/hosting-packages'
import { Route as AuthenticatedHostingRouteImport } from './routes/_authenticated/hosting'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDomainPricingRouteImport } from './routes/_authenticated/domain-pricing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAddonsRouteImport } from './routes/_authenticated/addons'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as MarketingHelpSlugRouteImport } from './routes/_marketing.help.$slug'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets_.$ticketId'
import { Route as AuthenticatedTeamMemberIdRouteImport } from './routes/_authenticated/team_.$memberId'
import { Route as AuthenticatedServicesServiceIdRouteImport } from './routes/_authenticated/services.$serviceId'
import { Route as AuthenticatedReceiptsPaymentIdRouteImport } from './routes/_authenticated/receipts.$paymentId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders_.$orderId'
import { Route as AuthenticatedKbArticleIdRouteImport } from './routes/_authenticated/kb_.$articleId'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices_.$invoiceId'
import { Route as AuthenticatedExpensesExpenseIdRouteImport } from './routes/_authenticated/expenses_.$expenseId'
import { Route as AuthenticatedDomainsDomainIdRouteImport } from './routes/_authenticated/domains_.$domainId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers_.$customerId'
import { Route as ApiPublicV1ServicesRouteImport } from './routes/api/public/v1/services'
import { Route as ApiPublicV1InvoicesRouteImport } from './routes/api/public/v1/invoices'
import { Route as ApiPublicHooksRenewalsRouteImport } from './routes/api/public/hooks/renewals'
import { Route as ApiPublicHooksRenewInvoicesRouteImport } from './routes/api/public/hooks/renew-invoices'
import { Route as ApiPublicHooksRegistrarCallbackRouteImport } from './routes/api/public/hooks/registrar-callback'
import { Route as ApiPublicHooksNotifyLeadRouteImport } from './routes/api/public/hooks/notify-lead'
import { Route as ApiPublicHooksEnforceOverdueRouteImport } from './routes/api/public/hooks/enforce-overdue'
import { Route as AuthenticatedOrderHostingPackageIdRouteImport } from './routes/_authenticated/order.hosting.$packageId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const PortalBkashCallbackRoute = PortalBkashCallbackRouteImport.update({
  id: '/bkash-callback',
  path: '/bkash-callback',
  getParentRoute: () => PortalRoute,
} as any)
const ClientSslczCallbackRoute = ClientSslczCallbackRouteImport.update({
  id: '/sslcz-callback',
  path: '/sslcz-callback',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBkashCallbackRoute = ClientBkashCallbackRouteImport.update({
  id: '/bkash-callback',
  path: '/bkash-callback',
  getParentRoute: () => ClientRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingWebHostingRoute = MarketingWebHostingRouteImport.update({
  id: '/web-hosting',
  path: '/web-hosting',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingVpsRoute = MarketingVpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSupportRoute = MarketingSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingResellerHostingRoute =
  MarketingResellerHostingRouteImport.update({
    id: '/reseller-hosting',
    path: '/reseller-hosting',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingRegisterDomainRoute = MarketingRegisterDomainRouteImport.update({
  id: '/register-domain',
  path: '/register-domain',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRefundRoute = MarketingRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpRoute = MarketingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingEmailHostingRoute = MarketingEmailHostingRouteImport.update({
  id: '/email-hosting',
  path: '/email-hosting',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDomainSearchRoute = MarketingDomainSearchRouteImport.update({
  id: '/domain-search',
  path: '/domain-search',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBdixHostingRoute = MarketingBdixHostingRouteImport.update({
  id: '/bdix-hosting',
  path: '/bdix-hosting',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthenticatedWhmServersRoute = AuthenticatedWhmServersRouteImport.update({
  id: '/whm-servers',
  path: '/whm-servers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceCatalogRoute =
  AuthenticatedServiceCatalogRouteImport.update({
    id: '/service-catalog',
    path: '/service-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellersRoute = AuthenticatedResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsAdminRoute =
  AuthenticatedReferralsAdminRouteImport.update({
    id: '/referrals-admin',
    path: '/referrals-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentSettingsRoute =
  AuthenticatedPaymentSettingsRouteImport.update({
    id: '/payment-settings',
    path: '/payment-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPageContentsRoute =
  AuthenticatedPageContentsRouteImport.update({
    id: '/page-contents',
    path: '/page-contents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOtherServicesRoute =
  AuthenticatedOtherServicesRouteImport.update({
    id: '/other-services',
    path: '/other-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKbRoute = AuthenticatedKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceSettingsRoute =
  AuthenticatedInvoiceSettingsRouteImport.update({
    id: '/invoice-settings',
    path: '/invoice-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostingPackagesRoute =
  AuthenticatedHostingPackagesRouteImport.update({
    id: '/hosting-packages',
    path: '/hosting-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostingRoute = AuthenticatedHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainPricingRoute =
  AuthenticatedDomainPricingRouteImport.update({
    id: '/domain-pricing',
    path: '/domain-pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddonsRoute = AuthenticatedAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MarketingHelpSlugRoute = MarketingHelpSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingHelpRoute,
} as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/tickets_/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamMemberIdRoute =
  AuthenticatedTeamMemberIdRouteImport.update({
    id: '/team_/$memberId',
    path: '/team/$memberId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesServiceIdRoute =
  AuthenticatedServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsPaymentIdRoute =
  AuthenticatedReceiptsPaymentIdRouteImport.update({
    id: '/receipts/$paymentId',
    path: '/receipts/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKbArticleIdRoute =
  AuthenticatedKbArticleIdRouteImport.update({
    id: '/kb_/$articleId',
    path: '/kb/$articleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices_/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesExpenseIdRoute =
  AuthenticatedExpensesExpenseIdRouteImport.update({
    id: '/expenses_/$expenseId',
    path: '/expenses/$expenseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainsDomainIdRoute =
  AuthenticatedDomainsDomainIdRouteImport.update({
    id: '/domains_/$domainId',
    path: '/domains/$domainId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV1ServicesRoute = ApiPublicV1ServicesRouteImport.update({
  id: '/api/public/v1/services',
  path: '/api/public/v1/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1InvoicesRoute = ApiPublicV1InvoicesRouteImport.update({
  id: '/api/public/v1/invoices',
  path: '/api/public/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewalsRoute = ApiPublicHooksRenewalsRouteImport.update({
  id: '/api/public/hooks/renewals',
  path: '/api/public/hooks/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRenewInvoicesRoute =
  ApiPublicHooksRenewInvoicesRouteImport.update({
    id: '/api/public/hooks/renew-invoices',
    path: '/api/public/hooks/renew-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRegistrarCallbackRoute =
  ApiPublicHooksRegistrarCallbackRouteImport.update({
    id: '/api/public/hooks/registrar-callback',
    path: '/api/public/hooks/registrar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyLeadRoute =
  ApiPublicHooksNotifyLeadRouteImport.update({
    id: '/api/public/hooks/notify-lead',
    path: '/api/public/hooks/notify-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnforceOverdueRoute =
  ApiPublicHooksEnforceOverdueRouteImport.update({
    id: '/api/public/hooks/enforce-overdue',
    path: '/api/public/hooks/enforce-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrderHostingPackageIdRoute =
  AuthenticatedOrderHostingPackageIdRouteImport.update({
    id: '/order/hosting/$packageId',
    path: '/order/hosting/$packageId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/addons': typeof AuthenticatedAddonsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domain-pricing': typeof AuthenticatedDomainPricingRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/invoice-settings': typeof AuthenticatedInvoiceSettingsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/kb': typeof AuthenticatedKbRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/other-services': typeof AuthenticatedOtherServicesRoute
  '/page-contents': typeof AuthenticatedPageContentsRoute
  '/payment-settings': typeof AuthenticatedPaymentSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals-admin': typeof AuthenticatedReferralsAdminRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/resellers': typeof AuthenticatedResellersRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/whm-servers': typeof AuthenticatedWhmServersRoute
  '/about': typeof MarketingAboutRoute
  '/bdix-hosting': typeof MarketingBdixHostingRoute
  '/contact': typeof MarketingContactRoute
  '/domain-search': typeof MarketingDomainSearchRoute
  '/email-hosting': typeof MarketingEmailHostingRoute
  '/help': typeof MarketingHelpRouteWithChildren
  '/privacy': typeof MarketingPrivacyRoute
  '/refund': typeof MarketingRefundRoute
  '/register-domain': typeof MarketingRegisterDomainRoute
  '/reseller-hosting': typeof MarketingResellerHostingRoute
  '/support': typeof MarketingSupportRoute
  '/terms': typeof MarketingTermsRoute
  '/vps': typeof MarketingVpsRoute
  '/web-hosting': typeof MarketingWebHostingRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/bkash-callback': typeof ClientBkashCallbackRoute
  '/client/sslcz-callback': typeof ClientSslczCallbackRoute
  '/portal/bkash-callback': typeof PortalBkashCallbackRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/kb/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/help/$slug': typeof MarketingHelpSlugRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/order/hosting/$packageId': typeof AuthenticatedOrderHostingPackageIdRoute
  '/api/public/hooks/enforce-overdue': typeof ApiPublicHooksEnforceOverdueRoute
  '/api/public/hooks/notify-lead': typeof ApiPublicHooksNotifyLeadRoute
  '/api/public/hooks/registrar-callback': typeof ApiPublicHooksRegistrarCallbackRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
  '/api/public/hooks/renewals': typeof ApiPublicHooksRenewalsRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/addons': typeof AuthenticatedAddonsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domain-pricing': typeof AuthenticatedDomainPricingRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/invoice-settings': typeof AuthenticatedInvoiceSettingsRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/kb': typeof AuthenticatedKbRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/other-services': typeof AuthenticatedOtherServicesRoute
  '/page-contents': typeof AuthenticatedPageContentsRoute
  '/payment-settings': typeof AuthenticatedPaymentSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals-admin': typeof AuthenticatedReferralsAdminRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/resellers': typeof AuthenticatedResellersRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/whm-servers': typeof AuthenticatedWhmServersRoute
  '/about': typeof MarketingAboutRoute
  '/bdix-hosting': typeof MarketingBdixHostingRoute
  '/contact': typeof MarketingContactRoute
  '/domain-search': typeof MarketingDomainSearchRoute
  '/email-hosting': typeof MarketingEmailHostingRoute
  '/help': typeof MarketingHelpRouteWithChildren
  '/privacy': typeof MarketingPrivacyRoute
  '/refund': typeof MarketingRefundRoute
  '/register-domain': typeof MarketingRegisterDomainRoute
  '/reseller-hosting': typeof MarketingResellerHostingRoute
  '/support': typeof MarketingSupportRoute
  '/terms': typeof MarketingTermsRoute
  '/vps': typeof MarketingVpsRoute
  '/web-hosting': typeof MarketingWebHostingRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/bkash-callback': typeof ClientBkashCallbackRoute
  '/client/sslcz-callback': typeof ClientSslczCallbackRoute
  '/portal/bkash-callback': typeof PortalBkashCallbackRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/kb/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/help/$slug': typeof MarketingHelpSlugRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/order/hosting/$packageId': typeof AuthenticatedOrderHostingPackageIdRoute
  '/api/public/hooks/enforce-overdue': typeof ApiPublicHooksEnforceOverdueRoute
  '/api/public/hooks/notify-lead': typeof ApiPublicHooksNotifyLeadRoute
  '/api/public/hooks/registrar-callback': typeof ApiPublicHooksRegistrarCallbackRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
  '/api/public/hooks/renewals': typeof ApiPublicHooksRenewalsRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/addons': typeof AuthenticatedAddonsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domain-pricing': typeof AuthenticatedDomainPricingRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/hosting': typeof AuthenticatedHostingRoute
  '/_authenticated/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/_authenticated/invoice-settings': typeof AuthenticatedInvoiceSettingsRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/kb': typeof AuthenticatedKbRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/other-services': typeof AuthenticatedOtherServicesRoute
  '/_authenticated/page-contents': typeof AuthenticatedPageContentsRoute
  '/_authenticated/payment-settings': typeof AuthenticatedPaymentSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals-admin': typeof AuthenticatedReferralsAdminRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/resellers': typeof AuthenticatedResellersRoute
  '/_authenticated/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/whm-servers': typeof AuthenticatedWhmServersRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/bdix-hosting': typeof MarketingBdixHostingRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/_marketing/domain-search': typeof MarketingDomainSearchRoute
  '/_marketing/email-hosting': typeof MarketingEmailHostingRoute
  '/_marketing/help': typeof MarketingHelpRouteWithChildren
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/refund': typeof MarketingRefundRoute
  '/_marketing/register-domain': typeof MarketingRegisterDomainRoute
  '/_marketing/reseller-hosting': typeof MarketingResellerHostingRoute
  '/_marketing/support': typeof MarketingSupportRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_marketing/vps': typeof MarketingVpsRoute
  '/_marketing/web-hosting': typeof MarketingWebHostingRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/bkash-callback': typeof ClientBkashCallbackRoute
  '/client/sslcz-callback': typeof ClientSslczCallbackRoute
  '/portal/bkash-callback': typeof PortalBkashCallbackRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_authenticated/customers_/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/domains_/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/_authenticated/expenses_/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/_authenticated/invoices_/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/kb_/$articleId': typeof AuthenticatedKbArticleIdRoute
  '/_authenticated/orders_/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/_authenticated/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/_authenticated/team_/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/_authenticated/tickets_/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_marketing/help/$slug': typeof MarketingHelpSlugRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/order/hosting/$packageId': typeof AuthenticatedOrderHostingPackageIdRoute
  '/api/public/hooks/enforce-overdue': typeof ApiPublicHooksEnforceOverdueRoute
  '/api/public/hooks/notify-lead': typeof ApiPublicHooksNotifyLeadRoute
  '/api/public/hooks/registrar-callback': typeof ApiPublicHooksRegistrarCallbackRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
  '/api/public/hooks/renewals': typeof ApiPublicHooksRenewalsRoute
  '/api/public/v1/invoices': typeof ApiPublicV1InvoicesRoute
  '/api/public/v1/services': typeof ApiPublicV1ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/addons'
    | '/announcements'
    | '/api-keys'
    | '/audit-log'
    | '/branding'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/domain-pricing'
    | '/domains'
    | '/expenses'
    | '/hosting'
    | '/hosting-packages'
    | '/invoice-settings'
    | '/invoices'
    | '/kb'
    | '/notifications'
    | '/orders'
    | '/other-services'
    | '/page-contents'
    | '/payment-settings'
    | '/profile'
    | '/referrals-admin'
    | '/renewals'
    | '/reports'
    | '/resellers'
    | '/service-catalog'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/webhooks'
    | '/whm-servers'
    | '/about'
    | '/bdix-hosting'
    | '/contact'
    | '/domain-search'
    | '/email-hosting'
    | '/help'
    | '/privacy'
    | '/refund'
    | '/register-domain'
    | '/reseller-hosting'
    | '/support'
    | '/terms'
    | '/vps'
    | '/web-hosting'
    | '/admin/login'
    | '/client/bkash-callback'
    | '/client/sslcz-callback'
    | '/portal/bkash-callback'
    | '/customers/$customerId'
    | '/domains/$domainId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/kb/$articleId'
    | '/orders/$orderId'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/services/$serviceId'
    | '/team/$memberId'
    | '/tickets/$ticketId'
    | '/help/$slug'
    | '/projects/'
    | '/order/hosting/$packageId'
    | '/api/public/hooks/enforce-overdue'
    | '/api/public/hooks/notify-lead'
    | '/api/public/hooks/registrar-callback'
    | '/api/public/hooks/renew-invoices'
    | '/api/public/hooks/renewals'
    | '/api/public/v1/invoices'
    | '/api/public/v1/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/client'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/addons'
    | '/announcements'
    | '/api-keys'
    | '/audit-log'
    | '/branding'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/domain-pricing'
    | '/domains'
    | '/expenses'
    | '/hosting'
    | '/hosting-packages'
    | '/invoice-settings'
    | '/invoices'
    | '/kb'
    | '/notifications'
    | '/orders'
    | '/other-services'
    | '/page-contents'
    | '/payment-settings'
    | '/profile'
    | '/referrals-admin'
    | '/renewals'
    | '/reports'
    | '/resellers'
    | '/service-catalog'
    | '/settings'
    | '/team'
    | '/tickets'
    | '/webhooks'
    | '/whm-servers'
    | '/about'
    | '/bdix-hosting'
    | '/contact'
    | '/domain-search'
    | '/email-hosting'
    | '/help'
    | '/privacy'
    | '/refund'
    | '/register-domain'
    | '/reseller-hosting'
    | '/support'
    | '/terms'
    | '/vps'
    | '/web-hosting'
    | '/admin/login'
    | '/client/bkash-callback'
    | '/client/sslcz-callback'
    | '/portal/bkash-callback'
    | '/customers/$customerId'
    | '/domains/$domainId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/kb/$articleId'
    | '/orders/$orderId'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/services/$serviceId'
    | '/team/$memberId'
    | '/tickets/$ticketId'
    | '/help/$slug'
    | '/projects'
    | '/order/hosting/$packageId'
    | '/api/public/hooks/enforce-overdue'
    | '/api/public/hooks/notify-lead'
    | '/api/public/hooks/registrar-callback'
    | '/api/public/hooks/renew-invoices'
    | '/api/public/hooks/renewals'
    | '/api/public/v1/invoices'
    | '/api/public/v1/services'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_marketing'
    | '/auth'
    | '/client'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/addons'
    | '/_authenticated/announcements'
    | '/_authenticated/api-keys'
    | '/_authenticated/audit-log'
    | '/_authenticated/branding'
    | '/_authenticated/coupons'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/domain-pricing'
    | '/_authenticated/domains'
    | '/_authenticated/expenses'
    | '/_authenticated/hosting'
    | '/_authenticated/hosting-packages'
    | '/_authenticated/invoice-settings'
    | '/_authenticated/invoices'
    | '/_authenticated/kb'
    | '/_authenticated/notifications'
    | '/_authenticated/orders'
    | '/_authenticated/other-services'
    | '/_authenticated/page-contents'
    | '/_authenticated/payment-settings'
    | '/_authenticated/profile'
    | '/_authenticated/referrals-admin'
    | '/_authenticated/renewals'
    | '/_authenticated/reports'
    | '/_authenticated/resellers'
    | '/_authenticated/service-catalog'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/tickets'
    | '/_authenticated/webhooks'
    | '/_authenticated/whm-servers'
    | '/_marketing/about'
    | '/_marketing/bdix-hosting'
    | '/_marketing/contact'
    | '/_marketing/domain-search'
    | '/_marketing/email-hosting'
    | '/_marketing/help'
    | '/_marketing/privacy'
    | '/_marketing/refund'
    | '/_marketing/register-domain'
    | '/_marketing/reseller-hosting'
    | '/_marketing/support'
    | '/_marketing/terms'
    | '/_marketing/vps'
    | '/_marketing/web-hosting'
    | '/admin/login'
    | '/client/bkash-callback'
    | '/client/sslcz-callback'
    | '/portal/bkash-callback'
    | '/_marketing/'
    | '/_authenticated/customers_/$customerId'
    | '/_authenticated/domains_/$domainId'
    | '/_authenticated/expenses_/$expenseId'
    | '/_authenticated/invoices_/$invoiceId'
    | '/_authenticated/kb_/$articleId'
    | '/_authenticated/orders_/$orderId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/receipts/$paymentId'
    | '/_authenticated/services/$serviceId'
    | '/_authenticated/team_/$memberId'
    | '/_authenticated/tickets_/$ticketId'
    | '/_marketing/help/$slug'
    | '/_authenticated/projects/'
    | '/_authenticated/order/hosting/$packageId'
    | '/api/public/hooks/enforce-overdue'
    | '/api/public/hooks/notify-lead'
    | '/api/public/hooks/registrar-callback'
    | '/api/public/hooks/renew-invoices'
    | '/api/public/hooks/renewals'
    | '/api/public/v1/invoices'
    | '/api/public/v1/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicHooksEnforceOverdueRoute: typeof ApiPublicHooksEnforceOverdueRoute
  ApiPublicHooksNotifyLeadRoute: typeof ApiPublicHooksNotifyLeadRoute
  ApiPublicHooksRegistrarCallbackRoute: typeof ApiPublicHooksRegistrarCallbackRoute
  ApiPublicHooksRenewInvoicesRoute: typeof ApiPublicHooksRenewInvoicesRoute
  ApiPublicHooksRenewalsRoute: typeof ApiPublicHooksRenewalsRoute
  ApiPublicV1InvoicesRoute: typeof ApiPublicV1InvoicesRoute
  ApiPublicV1ServicesRoute: typeof ApiPublicV1ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/portal/bkash-callback': {
      id: '/portal/bkash-callback'
      path: '/bkash-callback'
      fullPath: '/portal/bkash-callback'
      preLoaderRoute: typeof PortalBkashCallbackRouteImport
      parentRoute: typeof PortalRoute
    }
    '/client/sslcz-callback': {
      id: '/client/sslcz-callback'
      path: '/sslcz-callback'
      fullPath: '/client/sslcz-callback'
      preLoaderRoute: typeof ClientSslczCallbackRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bkash-callback': {
      id: '/client/bkash-callback'
      path: '/bkash-callback'
      fullPath: '/client/bkash-callback'
      preLoaderRoute: typeof ClientBkashCallbackRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/web-hosting': {
      id: '/_marketing/web-hosting'
      path: '/web-hosting'
      fullPath: '/web-hosting'
      preLoaderRoute: typeof MarketingWebHostingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/vps': {
      id: '/_marketing/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof MarketingVpsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/support': {
      id: '/_marketing/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof MarketingSupportRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/reseller-hosting': {
      id: '/_marketing/reseller-hosting'
      path: '/reseller-hosting'
      fullPath: '/reseller-hosting'
      preLoaderRoute: typeof MarketingResellerHostingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/register-domain': {
      id: '/_marketing/register-domain'
      path: '/register-domain'
      fullPath: '/register-domain'
      preLoaderRoute: typeof MarketingRegisterDomainRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/refund': {
      id: '/_marketing/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof MarketingRefundRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help': {
      id: '/_marketing/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MarketingHelpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/email-hosting': {
      id: '/_marketing/email-hosting'
      path: '/email-hosting'
      fullPath: '/email-hosting'
      preLoaderRoute: typeof MarketingEmailHostingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/domain-search': {
      id: '/_marketing/domain-search'
      path: '/domain-search'
      fullPath: '/domain-search'
      preLoaderRoute: typeof MarketingDomainSearchRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/bdix-hosting': {
      id: '/_marketing/bdix-hosting'
      path: '/bdix-hosting'
      fullPath: '/bdix-hosting'
      preLoaderRoute: typeof MarketingBdixHostingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_authenticated/whm-servers': {
      id: '/_authenticated/whm-servers'
      path: '/whm-servers'
      fullPath: '/whm-servers'
      preLoaderRoute: typeof AuthenticatedWhmServersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-catalog': {
      id: '/_authenticated/service-catalog'
      path: '/service-catalog'
      fullPath: '/service-catalog'
      preLoaderRoute: typeof AuthenticatedServiceCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resellers': {
      id: '/_authenticated/resellers'
      path: '/resellers'
      fullPath: '/resellers'
      preLoaderRoute: typeof AuthenticatedResellersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals-admin': {
      id: '/_authenticated/referrals-admin'
      path: '/referrals-admin'
      fullPath: '/referrals-admin'
      preLoaderRoute: typeof AuthenticatedReferralsAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-settings': {
      id: '/_authenticated/payment-settings'
      path: '/payment-settings'
      fullPath: '/payment-settings'
      preLoaderRoute: typeof AuthenticatedPaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/page-contents': {
      id: '/_authenticated/page-contents'
      path: '/page-contents'
      fullPath: '/page-contents'
      preLoaderRoute: typeof AuthenticatedPageContentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-services': {
      id: '/_authenticated/other-services'
      path: '/other-services'
      fullPath: '/other-services'
      preLoaderRoute: typeof AuthenticatedOtherServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kb': {
      id: '/_authenticated/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof AuthenticatedKbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice-settings': {
      id: '/_authenticated/invoice-settings'
      path: '/invoice-settings'
      fullPath: '/invoice-settings'
      preLoaderRoute: typeof AuthenticatedInvoiceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosting-packages': {
      id: '/_authenticated/hosting-packages'
      path: '/hosting-packages'
      fullPath: '/hosting-packages'
      preLoaderRoute: typeof AuthenticatedHostingPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosting': {
      id: '/_authenticated/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof AuthenticatedHostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domain-pricing': {
      id: '/_authenticated/domain-pricing'
      path: '/domain-pricing'
      fullPath: '/domain-pricing'
      preLoaderRoute: typeof AuthenticatedDomainPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addons': {
      id: '/_authenticated/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AuthenticatedAddonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_marketing/help/$slug': {
      id: '/_marketing/help/$slug'
      path: '/$slug'
      fullPath: '/help/$slug'
      preLoaderRoute: typeof MarketingHelpSlugRouteImport
      parentRoute: typeof MarketingHelpRoute
    }
    '/_authenticated/tickets_/$ticketId': {
      id: '/_authenticated/tickets_/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team_/$memberId': {
      id: '/_authenticated/team_/$memberId'
      path: '/team/$memberId'
      fullPath: '/team/$memberId'
      preLoaderRoute: typeof AuthenticatedTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/$serviceId': {
      id: '/_authenticated/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/$paymentId': {
      id: '/_authenticated/receipts/$paymentId'
      path: '/receipts/$paymentId'
      fullPath: '/receipts/$paymentId'
      preLoaderRoute: typeof AuthenticatedReceiptsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders_/$orderId': {
      id: '/_authenticated/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kb_/$articleId': {
      id: '/_authenticated/kb_/$articleId'
      path: '/kb/$articleId'
      fullPath: '/kb/$articleId'
      preLoaderRoute: typeof AuthenticatedKbArticleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices_/$invoiceId': {
      id: '/_authenticated/invoices_/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses_/$expenseId': {
      id: '/_authenticated/expenses_/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains_/$domainId': {
      id: '/_authenticated/domains_/$domainId'
      path: '/domains/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthenticatedDomainsDomainIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers_/$customerId': {
      id: '/_authenticated/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/services': {
      id: '/api/public/v1/services'
      path: '/api/public/v1/services'
      fullPath: '/api/public/v1/services'
      preLoaderRoute: typeof ApiPublicV1ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/invoices': {
      id: '/api/public/v1/invoices'
      path: '/api/public/v1/invoices'
      fullPath: '/api/public/v1/invoices'
      preLoaderRoute: typeof ApiPublicV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renewals': {
      id: '/api/public/hooks/renewals'
      path: '/api/public/hooks/renewals'
      fullPath: '/api/public/hooks/renewals'
      preLoaderRoute: typeof ApiPublicHooksRenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/renew-invoices': {
      id: '/api/public/hooks/renew-invoices'
      path: '/api/public/hooks/renew-invoices'
      fullPath: '/api/public/hooks/renew-invoices'
      preLoaderRoute: typeof ApiPublicHooksRenewInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/registrar-callback': {
      id: '/api/public/hooks/registrar-callback'
      path: '/api/public/hooks/registrar-callback'
      fullPath: '/api/public/hooks/registrar-callback'
      preLoaderRoute: typeof ApiPublicHooksRegistrarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-lead': {
      id: '/api/public/hooks/notify-lead'
      path: '/api/public/hooks/notify-lead'
      fullPath: '/api/public/hooks/notify-lead'
      preLoaderRoute: typeof ApiPublicHooksNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enforce-overdue': {
      id: '/api/public/hooks/enforce-overdue'
      path: '/api/public/hooks/enforce-overdue'
      fullPath: '/api/public/hooks/enforce-overdue'
      preLoaderRoute: typeof ApiPublicHooksEnforceOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/order/hosting/$packageId': {
      id: '/_authenticated/order/hosting/$packageId'
      path: '/order/hosting/$packageId'
      fullPath: '/order/hosting/$packageId'
      preLoaderRoute: typeof AuthenticatedOrderHostingPackageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddonsRoute: typeof AuthenticatedAddonsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainPricingRoute: typeof AuthenticatedDomainPricingRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedHostingRoute: typeof AuthenticatedHostingRoute
  AuthenticatedHostingPackagesRoute: typeof AuthenticatedHostingPackagesRoute
  AuthenticatedInvoiceSettingsRoute: typeof AuthenticatedInvoiceSettingsRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedKbRoute: typeof AuthenticatedKbRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedOtherServicesRoute: typeof AuthenticatedOtherServicesRoute
  AuthenticatedPageContentsRoute: typeof AuthenticatedPageContentsRoute
  AuthenticatedPaymentSettingsRoute: typeof AuthenticatedPaymentSettingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsAdminRoute: typeof AuthenticatedReferralsAdminRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResellersRoute: typeof AuthenticatedResellersRoute
  AuthenticatedServiceCatalogRoute: typeof AuthenticatedServiceCatalogRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedWhmServersRoute: typeof AuthenticatedWhmServersRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedDomainsDomainIdRoute: typeof AuthenticatedDomainsDomainIdRoute
  AuthenticatedExpensesExpenseIdRoute: typeof AuthenticatedExpensesExpenseIdRoute
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedKbArticleIdRoute: typeof AuthenticatedKbArticleIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedReceiptsPaymentIdRoute: typeof AuthenticatedReceiptsPaymentIdRoute
  AuthenticatedServicesServiceIdRoute: typeof AuthenticatedServicesServiceIdRoute
  AuthenticatedTeamMemberIdRoute: typeof AuthenticatedTeamMemberIdRoute
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedOrderHostingPackageIdRoute: typeof AuthenticatedOrderHostingPackageIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddonsRoute: AuthenticatedAddonsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainPricingRoute: AuthenticatedDomainPricingRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedHostingRoute: AuthenticatedHostingRoute,
  AuthenticatedHostingPackagesRoute: AuthenticatedHostingPackagesRoute,
  AuthenticatedInvoiceSettingsRoute: AuthenticatedInvoiceSettingsRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedKbRoute: AuthenticatedKbRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedOtherServicesRoute: AuthenticatedOtherServicesRoute,
  AuthenticatedPageContentsRoute: AuthenticatedPageContentsRoute,
  AuthenticatedPaymentSettingsRoute: AuthenticatedPaymentSettingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsAdminRoute: AuthenticatedReferralsAdminRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResellersRoute: AuthenticatedResellersRoute,
  AuthenticatedServiceCatalogRoute: AuthenticatedServiceCatalogRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedWhmServersRoute: AuthenticatedWhmServersRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedDomainsDomainIdRoute: AuthenticatedDomainsDomainIdRoute,
  AuthenticatedExpensesExpenseIdRoute: AuthenticatedExpensesExpenseIdRoute,
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedKbArticleIdRoute: AuthenticatedKbArticleIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedReceiptsPaymentIdRoute: AuthenticatedReceiptsPaymentIdRoute,
  AuthenticatedServicesServiceIdRoute: AuthenticatedServicesServiceIdRoute,
  AuthenticatedTeamMemberIdRoute: AuthenticatedTeamMemberIdRoute,
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedOrderHostingPackageIdRoute:
    AuthenticatedOrderHostingPackageIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MarketingHelpRouteChildren {
  MarketingHelpSlugRoute: typeof MarketingHelpSlugRoute
}

const MarketingHelpRouteChildren: MarketingHelpRouteChildren = {
  MarketingHelpSlugRoute: MarketingHelpSlugRoute,
}

const MarketingHelpRouteWithChildren = MarketingHelpRoute._addFileChildren(
  MarketingHelpRouteChildren,
)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBdixHostingRoute: typeof MarketingBdixHostingRoute
  MarketingContactRoute: typeof MarketingContactRoute
  MarketingDomainSearchRoute: typeof MarketingDomainSearchRoute
  MarketingEmailHostingRoute: typeof MarketingEmailHostingRoute
  MarketingHelpRoute: typeof MarketingHelpRouteWithChildren
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingRefundRoute: typeof MarketingRefundRoute
  MarketingRegisterDomainRoute: typeof MarketingRegisterDomainRoute
  MarketingResellerHostingRoute: typeof MarketingResellerHostingRoute
  MarketingSupportRoute: typeof MarketingSupportRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingVpsRoute: typeof MarketingVpsRoute
  MarketingWebHostingRoute: typeof MarketingWebHostingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBdixHostingRoute: MarketingBdixHostingRoute,
  MarketingContactRoute: MarketingContactRoute,
  MarketingDomainSearchRoute: MarketingDomainSearchRoute,
  MarketingEmailHostingRoute: MarketingEmailHostingRoute,
  MarketingHelpRoute: MarketingHelpRouteWithChildren,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingRefundRoute: MarketingRefundRoute,
  MarketingRegisterDomainRoute: MarketingRegisterDomainRoute,
  MarketingResellerHostingRoute: MarketingResellerHostingRoute,
  MarketingSupportRoute: MarketingSupportRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingVpsRoute: MarketingVpsRoute,
  MarketingWebHostingRoute: MarketingWebHostingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface ClientRouteChildren {
  ClientBkashCallbackRoute: typeof ClientBkashCallbackRoute
  ClientSslczCallbackRoute: typeof ClientSslczCallbackRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBkashCallbackRoute: ClientBkashCallbackRoute,
  ClientSslczCallbackRoute: ClientSslczCallbackRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface PortalRouteChildren {
  PortalBkashCallbackRoute: typeof PortalBkashCallbackRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBkashCallbackRoute: PortalBkashCallbackRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicHooksEnforceOverdueRoute: ApiPublicHooksEnforceOverdueRoute,
  ApiPublicHooksNotifyLeadRoute: ApiPublicHooksNotifyLeadRoute,
  ApiPublicHooksRegistrarCallbackRoute: ApiPublicHooksRegistrarCallbackRoute,
  ApiPublicHooksRenewInvoicesRoute: ApiPublicHooksRenewInvoicesRoute,
  ApiPublicHooksRenewalsRoute: ApiPublicHooksRenewalsRoute,
  ApiPublicV1InvoicesRoute: ApiPublicV1InvoicesRoute,
  ApiPublicV1ServicesRoute: ApiPublicV1ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
