/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServiceCatalogRouteImport } from './routes/_authenticated/service-catalog'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOtherServicesRouteImport } from './routes/_authenticated/other-services'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHostingPackagesRouteImport } from './routes/_authenticated/hosting-packages'
import { Route as AuthenticatedHostingRouteImport } from './routes/_authenticated/hosting'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedTeamMemberIdRouteImport } from './routes/_authenticated/team.$memberId'
import { Route as AuthenticatedServicesServiceIdRouteImport } from './routes/_authenticated/services.$serviceId'
import { Route as AuthenticatedReceiptsPaymentIdRouteImport } from './routes/_authenticated/receipts.$paymentId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedExpensesExpenseIdRouteImport } from './routes/_authenticated/expenses.$expenseId'
import { Route as AuthenticatedDomainsDomainIdRouteImport } from './routes/_authenticated/domains.$domainId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as ApiPublicHooksRenewInvoicesRouteImport } from './routes/api/public/hooks/renew-invoices'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceCatalogRoute =
  AuthenticatedServiceCatalogRouteImport.update({
    id: '/service-catalog',
    path: '/service-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtherServicesRoute =
  AuthenticatedOtherServicesRouteImport.update({
    id: '/other-services',
    path: '/other-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostingPackagesRoute =
  AuthenticatedHostingPackagesRouteImport.update({
    id: '/hosting-packages',
    path: '/hosting-packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHostingRoute = AuthenticatedHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamMemberIdRoute =
  AuthenticatedTeamMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedTeamRoute,
  } as any)
const AuthenticatedServicesServiceIdRoute =
  AuthenticatedServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsPaymentIdRoute =
  AuthenticatedReceiptsPaymentIdRouteImport.update({
    id: '/receipts/$paymentId',
    path: '/receipts/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedExpensesExpenseIdRoute =
  AuthenticatedExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedDomainsDomainIdRoute =
  AuthenticatedDomainsDomainIdRouteImport.update({
    id: '/$domainId',
    path: '/$domainId',
    getParentRoute: () => AuthenticatedDomainsRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const ApiPublicHooksRenewInvoicesRoute =
  ApiPublicHooksRenewInvoicesRouteImport.update({
    id: '/api/public/hooks/renew-invoices',
    path: '/api/public/hooks/renew-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/hosting': typeof AuthenticatedHostingRoute
  '/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/other-services': typeof AuthenticatedOtherServicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/hosting': typeof AuthenticatedHostingRoute
  '/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/orders': typeof AuthenticatedOrdersRoute
  '/other-services': typeof AuthenticatedOtherServicesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/_authenticated/hosting': typeof AuthenticatedHostingRoute
  '/_authenticated/hosting-packages': typeof AuthenticatedHostingPackagesRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/other-services': typeof AuthenticatedOtherServicesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/service-catalog': typeof AuthenticatedServiceCatalogRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRouteWithChildren
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/_authenticated/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/receipts/$paymentId': typeof AuthenticatedReceiptsPaymentIdRoute
  '/_authenticated/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/_authenticated/team/$memberId': typeof AuthenticatedTeamMemberIdRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/api/public/hooks/renew-invoices': typeof ApiPublicHooksRenewInvoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/customers'
    | '/dashboard'
    | '/domains'
    | '/expenses'
    | '/hosting'
    | '/hosting-packages'
    | '/invoices'
    | '/orders'
    | '/other-services'
    | '/profile'
    | '/service-catalog'
    | '/settings'
    | '/team'
    | '/customers/$customerId'
    | '/domains/$domainId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/services/$serviceId'
    | '/team/$memberId'
    | '/projects/'
    | '/api/public/hooks/renew-invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/customers'
    | '/dashboard'
    | '/domains'
    | '/expenses'
    | '/hosting'
    | '/hosting-packages'
    | '/invoices'
    | '/orders'
    | '/other-services'
    | '/profile'
    | '/service-catalog'
    | '/settings'
    | '/team'
    | '/customers/$customerId'
    | '/domains/$domainId'
    | '/expenses/$expenseId'
    | '/invoices/$invoiceId'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/services/$serviceId'
    | '/team/$memberId'
    | '/projects'
    | '/api/public/hooks/renew-invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/expenses'
    | '/_authenticated/hosting'
    | '/_authenticated/hosting-packages'
    | '/_authenticated/invoices'
    | '/_authenticated/orders'
    | '/_authenticated/other-services'
    | '/_authenticated/profile'
    | '/_authenticated/service-catalog'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/domains/$domainId'
    | '/_authenticated/expenses/$expenseId'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/receipts/$paymentId'
    | '/_authenticated/services/$serviceId'
    | '/_authenticated/team/$memberId'
    | '/_authenticated/projects/'
    | '/api/public/hooks/renew-invoices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
  ApiPublicHooksRenewInvoicesRoute: typeof ApiPublicHooksRenewInvoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-catalog': {
      id: '/_authenticated/service-catalog'
      path: '/service-catalog'
      fullPath: '/service-catalog'
      preLoaderRoute: typeof AuthenticatedServiceCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-services': {
      id: '/_authenticated/other-services'
      path: '/other-services'
      fullPath: '/other-services'
      preLoaderRoute: typeof AuthenticatedOtherServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosting-packages': {
      id: '/_authenticated/hosting-packages'
      path: '/hosting-packages'
      fullPath: '/hosting-packages'
      preLoaderRoute: typeof AuthenticatedHostingPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosting': {
      id: '/_authenticated/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof AuthenticatedHostingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/$memberId': {
      id: '/_authenticated/team/$memberId'
      path: '/$memberId'
      fullPath: '/team/$memberId'
      preLoaderRoute: typeof AuthenticatedTeamMemberIdRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/services/$serviceId': {
      id: '/_authenticated/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/$paymentId': {
      id: '/_authenticated/receipts/$paymentId'
      path: '/receipts/$paymentId'
      fullPath: '/receipts/$paymentId'
      preLoaderRoute: typeof AuthenticatedReceiptsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/expenses/$expenseId': {
      id: '/_authenticated/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/domains/$domainId': {
      id: '/_authenticated/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthenticatedDomainsDomainIdRouteImport
      parentRoute: typeof AuthenticatedDomainsRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/api/public/hooks/renew-invoices': {
      id: '/api/public/hooks/renew-invoices'
      path: '/api/public/hooks/renew-invoices'
      fullPath: '/api/public/hooks/renew-invoices'
      preLoaderRoute: typeof ApiPublicHooksRenewInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedDomainsRouteChildren {
  AuthenticatedDomainsDomainIdRoute: typeof AuthenticatedDomainsDomainIdRoute
}

const AuthenticatedDomainsRouteChildren: AuthenticatedDomainsRouteChildren = {
  AuthenticatedDomainsDomainIdRoute: AuthenticatedDomainsDomainIdRoute,
}

const AuthenticatedDomainsRouteWithChildren =
  AuthenticatedDomainsRoute._addFileChildren(AuthenticatedDomainsRouteChildren)

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesExpenseIdRoute: typeof AuthenticatedExpensesExpenseIdRoute
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesExpenseIdRoute: AuthenticatedExpensesExpenseIdRoute,
}

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamMemberIdRoute: typeof AuthenticatedTeamMemberIdRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamMemberIdRoute: AuthenticatedTeamMemberIdRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRouteWithChildren
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren
  AuthenticatedHostingRoute: typeof AuthenticatedHostingRoute
  AuthenticatedHostingPackagesRoute: typeof AuthenticatedHostingPackagesRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedOtherServicesRoute: typeof AuthenticatedOtherServicesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServiceCatalogRoute: typeof AuthenticatedServiceCatalogRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedReceiptsPaymentIdRoute: typeof AuthenticatedReceiptsPaymentIdRoute
  AuthenticatedServicesServiceIdRoute: typeof AuthenticatedServicesServiceIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRouteWithChildren,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
  AuthenticatedHostingRoute: AuthenticatedHostingRoute,
  AuthenticatedHostingPackagesRoute: AuthenticatedHostingPackagesRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedOtherServicesRoute: AuthenticatedOtherServicesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServiceCatalogRoute: AuthenticatedServiceCatalogRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedReceiptsPaymentIdRoute: AuthenticatedReceiptsPaymentIdRoute,
  AuthenticatedServicesServiceIdRoute: AuthenticatedServicesServiceIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
  ApiPublicHooksRenewInvoicesRoute: ApiPublicHooksRenewInvoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
